url: https://cropquest.github.io
baseurl:

# Site settings
title: Crop Quest Tech Team
email: dev@cropquest.com
description: "Tech Team at Crop Quest"


# Team names, titles and social links
people:
- name: Nathan Woydziak
  pic: 1
  position: Tech Team / Precision Ag Manager
  location: Hoisington, KS
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nwoydz

- name: Bryce Johnston
  pic: 1
  position: Lead Developer / SysAdmin
  location: Manhattan, KS
  social:
    - title: github
      url: https://github.com/beaorn
    - title: stack-overflow
      url: https://stackoverflow.com/users/5086701/beaorn

- name: Josh DaVee
  pic: 1
  position: Jr. Developer
  location: Lawrence, KS
  social:
    - title: github
      url: https://github.com/jdavee

- name: Colt Petty
  pic: 1
  position: IT Specialist
  location: Dodge City, KS
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/colt-petty-9134b9b3

- name: John Gibson
  pic: 1
  position: Precision Ag Specialist
  location: Dodge City, KS
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/john-gibson-0a444b115

- name: Chris Pope
  pic: 1
  position: Precision Ag Specialist
  location: Hoxie, KS

- name: Kevin Hecht
  pic: 1
  position: Precision Ag Specialist
  location: Ulysses, KS

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/CropQuestInc
  - title: facebook
    url: https://www.facebook.com/cropquest
  - title: github
    url: http://github.com/CropQuest
  - title: stack-overflow
    url: https://stackoverflow.com/jobs/companies/crop-quest

# Postal address (add as many lines as necessary)
address:
  - line: 1204 Frontview St.
  - line: Dodge City, KS

# Build settings
markdown: kramdown
permalink: pretty
